site_name: kibad llm
site_url: https://sitename.example
#
site_author: Your name (or your organization/company/team)
#
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

plugins:
  - mkdocstrings

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
