# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: local

callbacks:
  save_job_return:
    _target_: kibad_llm.hydra_callbacks.SaveJobReturnValueCallback
    replace_existing_overrides: false
    sort_markdown_columns: true
    filenames:
      - job_return_value.json
      - job_return_value.md
    integrate_multirun_result: false
    multirun_add_overrides_as_dict: true
    multirun_convert_job_ids: true
    multirun_show_file_contents: [job_return_value.md]
    # file names contain the default separator ("-"), so we change it here to avoid conflicts
    multirun_overrides_separator: "#"
    multirun_aggregator_blacklist: ["min", "25%", "50%", "75%", "max"]

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/runs/${paths.run_subdir}
sweep:
  dir: ${paths.log_dir}/multiruns/${paths.run_subdir}
  subdir: ${hydra.job.num}
