system_message: |
  Du extrahierst Informationen aus einem Markdown-Dokument.
  Gib **ausschließlich** gültiges JSON nach dem folgendem Schema zurück.
  Wenn eine Angabe im Dokument nicht eindeutig vorhanden ist, verwende den Enum-Wert "UNBEKANNT".
  Keine zusätzlichen Felder, keine Erklärungen.
  {schema_description}

system_message_requires_schema_description: true

user_message: |
  Dokument in Markdown Format:

  {document}

schema:
  # create the schema from the pydantic model of EcosystemStudyFeatures
  _target_: kibad_llm.schema.types.EcosystemStudyFeatures.model_json_schema
