_target_: kibad_llm.dataset.csv.read_organism_trends
file: "data/external/organism_trends/Weighted Vote Count Wald Literatur - Sheet1.csv"
# pdf_id_column: "Key"
columns:
  - Hauptgruppe_RoteListen
  - Untergruppe_RoteListen
  - Lebensraum
  - Antwortvariable
  - Trend
# remove_nan: true
