# extraction workflow that repeats the extraction n times and aggregates the results
# per key by majority voting

defaults:
  - llm: gpt_oss_20b

_target_: kibad_llm.extractors.RepeatingExtractor
n: 3  # number of repetitions
return_as_list:
  - structured
  - error
  - response_content
return_reasoning: False
