# simple extraction workflow based on a single LLM call using a prompt template

defaults:
  - llm: gpt_oss_20b

_target_: kibad_llm.extractors.extract_from_text_lenient
# mark as partial since it is a function (and not a class to be instantiated)
_partial_: True
return_reasoning: False
