# Template for conditional extraction with schema. We put the document in the system message
# and the schema description in the user message since the conditional extractor adds the
# system message just once but the user message for each schema.

system_message: |
  Lies das folgende Markdown-Dokument sorgfältig durch, damit du die darin enthaltenen
  biodiversitätsbezogenen Informationen extrahieren kannst.

  Document in Markdown Format:

  {document}

user_message: |
  Extrahiere die folgenden Informationen aus dem gegebenen Markdown-Dokument.
  Wenn bereits Informationen extrahiert wurden, kannst du diese als Kontext für die aktuelle Extraktion nutzen.
  Gib **ausschließlich** gültiges JSON nach dem folgendem Schema zurück.
  Keine zusätzlichen Felder, keine Erklärungen.

  {schema_description}

schema_description_placeholder: schema_description
document_placeholder: document
