# extraction workflow that repeats the extraction for each item in the overrides list
# and aggregates the results per key by union

defaults:
  - llm: gpt_oss_20b

_target_: kibad_llm.extractors.UnionExtractor
overrides: ???  # list of extraction workflows to union
return_as_list:  # for these fields, return a list of results from each extraction
  # - structured
  - error
  # - response_content
  # - reasoning_content
  # - messages
  # - messages_formatted
return_reasoning: False
