# This configuration file defines a ConditionalUnionExtractor that uses two different
# schemata for extracting information. The llm is queried sequentially with each schema,
# but the result from previous extractions is passed as history to condition the subsequent
# extractions.

defaults:
  - union
  # special template where the document is in the system message and the schema description
  # is in the user message since the conditional extractor adds the system message just once,
  # but the user message for each schema.
  - override prompt_template: schema_in_user_message

_target_: kibad_llm.extractors.ChunkingExtractor

tokenizer:
  _target_: kibad_llm.extractors.chunking_helpers.RegexTokenizer
  _partial_: true
