# This configuration file defines a ConditionalUnionExtractor that uses two different
# schemata for extracting information. The llm is queried sequentially with each schema,
# but the result from previous extractions is passed as history to condition the subsequent
# extractions.

defaults:
  - llm: gpt_oss_20b
  # special template where the document is in the system message and the schema description
  # is in the user message since the conditional extractor adds the system message just once,
  # but the user message for each schema.
  - _template_with_schema_in_user_message

_target_: kibad_llm.extractors.ConditionalUnionExtractor
return_as_list:  # for these fields, return a list of results from each extraction
  # - structured
  - error
  # - response_content
  # - reasoning_content
  # - messages
  # - messages_formatted
return_reasoning: False
return_messages: False

# Use two dummy schemata (...Simple) per default. Overrides is a list, so setting it
# somewhere else will completely replace the list.
overrides:
  - schema:
      # create the schema from the pydantic model EcosystemStudyFeaturesSimple
      _target_: kibad_llm.schema.types.EcosystemStudyFeaturesSimple.model_json_schema
      by_alias: false
  - schema:
      # create the schema from the pydantic model EcosystemStudyFeaturesCompoundsSimple
      _target_: kibad_llm.schema.types.EcosystemStudyFeaturesCompoundsSimple.model_json_schema
      by_alias: false
