# extraction workflow that repeats the extraction n times and aggregates the results
# per key by majority voting

defaults:
  - schema: faktencheck_simple
  - aggregator: majority_vote
  - llm: gpt_oss_20b
  - prompt_template: default
  - request_parameters: default

_target_: kibad_llm.extractors.RepeatingExtractor
n: 3  # number of repetitions
# for these fields, return a list of results from each repetition
return_as_list:
  # - structured
  - errors
  # - response_content
  - reasoning_content
  # - messages
  # - messages_formatted

# general return options (see simple extractor for details)
return_reasoning: True
return_messages: False
return_messages_formatted: False
