# simple extraction workflow based on a single LLM call using a prompt template

defaults:
  - schema: faktencheck_simple
  - llm: gpt_oss_20b
  - prompt_template: default
  - request_parameters: default

_target_: kibad_llm.extractors.extract_from_text_lenient
# mark as partial since it is a function (and not a class to be instantiated)
_partial_: True

# return options
return_reasoning: True
return_messages: False
return_messages_formatted: False
