# extraction workflow that repeats the extraction for each item in the overrides list
# and aggregates the results per key unanimously (i.e., only if all extractions agree
# on the same value, otherwise an error is raised)

defaults:
  - aggregator: unanimous
  - llm: gpt_oss_20b
  - prompt_template: default
  - request_parameters: default

_target_: kibad_llm.extractors.UnionExtractor

# Overrides need to be dictionaries that will get instantiated and then passed as kwargs
# to the respective base extractor. Thus, no hydra-like merging for individual kwargs is
# possible (e.g., "by_alias: false" is not derived from the base extractor config, but
# needs to be repeated for each schema).
#
# Use two dummy schemata (...Simple) per default. Overrides is a list, so setting it
# somewhere else will completely replace the list.
overrides:
  - schema:
      # create the schema from the pydantic model EcosystemStudyFeaturesSimple
      _target_: kibad_llm.schema.types.EcosystemStudyFeaturesSimple.model_json_schema
      by_alias: false
  - schema:
      # create the schema from the pydantic model EcosystemStudyFeaturesCompoundsSimple
      _target_: kibad_llm.schema.types.EcosystemStudyFeaturesCompoundsSimple.model_json_schema
      by_alias: false

# for these fields, return a list of results from each extraction
return_as_list:
  # - structured
  - errors
  # - response_content
  - reasoning_content
  # - messages
  # - messages_formatted

# general return options (see simple extractor for details)
return_reasoning: True
return_messages: False
return_messages_formatted: False
