# @package _global_

# Configuration for evaluating predictions against gold reference data via a metric.
#
# In detail:
#  - Entries in the predictions are taken from the "structured" field produced by the LLM in predict.py
#    and individual fields (which are based on the json schema compiled from schema.types.EcosystemStudyFeatures)
#    are mapped via the json_paths_mapping below.
#  - Entries in the references are taken from the json produced by db_converter.py (from the Faktencheck-DB),
#    but flattened (dicts as well as list levels).
#  - Prediction and reference entries are matched based on the PDF file_name and zotitem_ptr_id, respectively.
#  - Per default, uses the "f1_single" metric to compute F1 scores far a selected field of single-label
#    classification (see configs/metrics/f1_single.yaml for details). See configs/metrics/ for other
#    available metrics.
#
# Usage:
#    python -m kibad_llm.evaluate predictions_file=path/to/predictions.jsonl references_file=path/to/references.jsonl

defaults:
  - metric: f1_single

# Path to the JSONL file containing predictions to evaluate, e.g., produced by predict.py.
predictions_file: ???
# Path to the JSONL file containing gold reference data for evaluation,
# e.g., produced by data_integration/db_converter.py from the Faktencheck-DB.
references_file: ???

# map the field names used in the json schema to the json paths (keys) in the (flattened) reference jsonl file
# see column "Pfad im JSONL der konvertierten Faktencheck-DB" in table
# https://docs.google.com/spreadsheets/d/1MyEZTLOm85ZNxuTSHxwJLxaAXiCGLt-mMozUkBlGzJE/edit?gid=0#gid=0
# but also the result of the data_integration/json_db_summary.py script:
# https://github.com/DFKI-NLP/kibad-llm/pull/31#issuecomment-3418782905
json_paths_mapping:
  Bundesland: "location/federal_state"
  # TODO: it looks like we have "Lebensräume" in the table instead
  Lebensraum: "TODO"
  # TODO: it looks like we have "Großräume" in the table instead
  Naturgroßraum: "TODO"
  Ökosystemtyp: "ecosystem_type/term"
