# @package _global_

# Configuration for evaluating predictions against gold reference data via a metric.
#
# In detail:
#  - Entries in the predictions are taken from the "structured" field produced by the LLM in predict.py
#    and individual fields (which are based on the json schema compiled from schema.types.EcosystemStudyFeatures).
#    See dataset/predictions/extraction_result.yaml for details.
#  - Entries in the references are taken from the json produced by db_converter.py (from the Faktencheck-DB).
#    See dataset/references/faktencheck_db_converted.yaml for details.
#  - Prediction and reference entries are matched based on the PDF file_name and zotitem_ptr_id, respectively.
#    See dataset/faktencheck.yaml for details.
#  - Per default, uses the "f1" metric to compute F1 scores far a selected field of single- or multi-label
#    classification (see configs/metrics/f1.yaml for details). See configs/metrics/ for other
#    available metrics.
#
# Usage:
#    python -m kibad_llm.evaluate \
#      dataset.predictions.file=path/to/predictions.jsonl

defaults:
  - _self_
  - paths: evaluate
  - hydra: default
  # this needs to return a dataset with 'prediction' and 'reference' entries
  - dataset: faktencheck
  # this needs to return an instance of kibad_llm.metric.Metric
  - metric: f1_micro
  # Experiment configs allow to define specific evaluation setups. This is useful for complex setups to simplify
  # commands, but especially recommended when some parameters depend on each other.
  # Note that multiple experiments (if they do not require other dependent settings) can be easily executed
  # in a single multi-run for fast reproducibility.
  - experiment/evaluate: null

# name of the run, used in logging and as a subdir of log_dir
name: "default"

# List of log directories containing prediction runs to evaluate.
# If set, replaces dataset.predictions.log in multi-run mode.
predictions_multirun_logs: null
# Adjust hydra multi-run settings to run over all subdirectories of the specified
# log directories. Note that dataset.predictions.log takes precedence if both are set.
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      # Get all directories under the specified log directories that contain a job_return_value.json file,
      # but only return the leafs (i.e. exclude multi-run outputs).
      dataset.predictions.log: "${get_directories_with_file:${predictions_multirun_logs},job_return_value.json,True}"
