# @package _global_

# Configuration for running classification based data extraction on a set of PDF files. The extracted
# data is saved in JSONL format. See models and templates config subdirectories for available model
# settings and prompt templates.
# Uses:
# - pymupdf4llm for PDF text extraction,
# - LlamaIndex to interact with a local LLM model to classify and extract structured data, and
# - datasets for pipeline management and caching.
#
# Usage:
#   python -m kibad_llm.predict pdf_directory=path/to/pdf/files


defaults:
  - _self_
  - paths: default
  - hydra: default
  # The PDF reader gets the PDF path as positional argument and needs to return a string with the extracted text.
  - pdf_reader: pymupdf4llm
  # The extractor gets the 'text' and 'text_id' as positional parameters
  # and needs to return a dictionary with the extracted data.
  - extractor: simple_with_schema
  # Experiment configs allow to define specific inference setups. This is useful for complex setups to simplify
  # commands, but especially recommended when some parameters depend on each other.
  # Note that multiple experiments (if they do not require other dependent settings) can be easily executed
  # in a single multi-run for fast reproducibility.
  - experiment/predict: null

print_config: True

# ignore_warnings: True

# name of the run, used in logging and as a subdir of log_dir
name: "default"

# path to the directory containing the PDF files to process
pdf_directory: ???
# path to the directory where the JSONL file with the predictions will be saved
output_dir: ${paths.prediction_save_dir}

# enable to process only a subset of the data, useful for debugging
fast_dev_run: False
# set True to enable caching of extraction results, useful for debugging
extraction_caching: False
# set True to enable storing the text in predictions, costs loads of storage
store_text_in_predictions: False
