# @package _global_

defaults:
  - _self_
  - model: gpt_oss_20b
  - paths: default
  - template: v1_with_schema
  - hydra: default

print_config: True

# ignore_warnings: True

# name of the run, used in logging and as a subdir of log_dir
name: "default"

pdf_directory: ???
output_file: ${paths.prediction_save_dir}/predictions.jsonl

# enable to process only a subset of the data, useful for debugging
fast_dev_run: False
