# @package _global_

# Configuration for running classification based data extraction on a set of PDF files. The extracted
# data is saved in JSONL format. See models and templates config subdirectories for available model
# settings and prompt templates.
# Uses:
# - pymupdf4llm for PDF text extraction,
# - LlamaIndex to interact with a local LLM model to classify and extract structured data, and
# - datasets for pipeline management and caching.
#
# Usage:
#   python -m kibad_llm.predict pdf_directory=path/to/pdf/files


defaults:
  - _self_
  - paths: default
  - hydra: default
  # The PDF reader gets the PDF path as positional argument and needs to return a string with the extracted text.
  - pdf_reader: pymupdf4llm
  # The extractor gets the 'text' and 'text_id' as positional parameters
  # and needs to return a dictionary with the extracted data.
  - extractor: repeat_with_schema

print_config: True

# ignore_warnings: True

# name of the run, used in logging and as a subdir of log_dir
name: "default"

# path to the directory containing the PDF files to process
pdf_directory: ???
# path to the JSONL file where the predictions will be saved
output_file: ${paths.prediction_save_dir}/predictions.jsonl

# enable to process only a subset of the data, useful for debugging
fast_dev_run: False
# enable to disable caching of extraction results, useful for debugging
disable_extraction_caching: False
