# Template to extract information from ecosystem study documents in Markdown with
# guided decoding based on a JSON schema.
# Uses the pydantic model `EcosystemStudyFeaturesSimple` to define the schema and a description
# derived from that schema (model field docstrings and value enums) to guide the LLM.

system_message: |
  Du extrahierst Informationen aus einem Markdown-Dokument.
  Gib **ausschließlich** gültiges JSON nach dem folgendem Schema zurück.
  Keine zusätzlichen Felder, keine Erklärungen.
  {schema_description}

user_message: |
  Dies ist der vorhergehende Abschnitt, nur als Kontext!

  {previous_document_chunk}

  Dies ist der aktuelle Abschnitt aus dem du extrahieren sollst:

  {document}

# This indicates where to insert the schema description and the document text in the system and/or user message.
# The schema_description_placeholder should be present in a message if a schema is provided.
# The document_placeholder needs to be present in either the system or user message.
schema_description_placeholder: schema_description
document_placeholder: document
