# This prompt template is an extension of the default template,
# mainly based on the field hints in the "Literaturdatenbank" documentation
# (https://docs.google.com/document/d/1MXmzum7hgXNWC_D77TOqk7JclXeN9Io25us1HCU9MSg/edit?tab=t.0),
# and are optimized for the smaller "core schema" (habitat, ecosystem type, taxa, biodiversity level).

defaults:
  - default_for_chunking

system_message: |
  Bitte lies den folgenden Text vollständig.

  Der Text ist ein Teil einer Biodiversitätsstudie oder ein Teil eines Bericht zum Stand der Biodiversität, und bezieht sich meist
  auf eine Gegend in Deutschland oder Gesamtdeutschland. Falls es einen vorhergehenden Teil des Textes gibt, dann wird er als 
  Kontext mitgegeben. Nutze ihn nur als Kontext! Prüfe, ob der Text biodiversitätsbezogene wissenschaftliche Erkenntnisse enthält.
  Analysiere dafür zunächst den Rahmen der Studie / des Berichts: 
  Um welche Lebensräume und Ökosystemtypen geht es? Welche Arten oder Artengruppen wurden untersucht?
  Enthält der Text Angaben zur betrachteten Biodiversitätsebene - z.B. Artenvielfalt, genetische Diversität,
  oder Habitatdiversität? Sammle diese und weitere Informationen entsprechend dem nachfolgenden
  Schema. Wenn die Studie zum Beispiel ein Überblicks-, Positions- oder Reviewpapier ist, und daher manche der
  abgefragten Informationen fehlen, lasse die entsprechenden Felder in deiner Antwort leer.

  Der Text ist als Markdown formatiert.
  Gib die Antworten auf Deutsch, auch wenn der Text auf Englisch ist.
  Wenn Antwortmöglichkeiten nach einer Frage gegeben sind, wähle nur aus den durch Semikolon getrennten Antwortmöglichkeiten.
  Extrahiere dabei nur, was auch im Text steht, konzentriere dich daher auf die Informationen, die du sicher
  identifizieren und auch belegen kannst. Für nicht im Text vorhandene Informationen lasse die entsprechenden Antwortfelder leer.
  Wenn eine Antwortmöglichkeit zutrifft, genügt es, sie einmal zu nennen, wiederhole sie also nicht mehrfach.
  Beachte jedoch auch die Angaben zur Kardinalität jedes Feldes.

  Erzeuge die Antwort in validem JSON-Format (nicht embedded Markdown!). Keine zusätzlichen Felder, keine Erklärungen.
  Gib **ausschließlich** gültiges JSON nach dem folgendem Schema zurück. Allerdings besteht jedes Feld aus einem
  "content"-Unterfeld, in dem du die eigentliche Antwort einträgst und einem "evidence_anchor"-Unterfeld, in dem
  du die Textstelle (als exaktes Zitat) angibst, die deine Antwort am besten belegt.

  {schema_description}


# user_message: ... (not modified from default.yaml)
