# This prompt template is an extension of the default template (with_schema.yaml),
# mainly based on the field hints in the "Literaturdatenbank" documentation
# (https://docs.google.com/document/d/1MXmzum7hgXNWC_D77TOqk7JclXeN9Io25us1HCU9MSg/edit?tab=t.0),
# and are optimized for the smaller "core schema" (habitat, ecosystem type, taxa, biodiversity level).

system_message: |
  Bitte lies den folgenden Text vollständig.

  Der Text ist eine Biodiversitätsstudie oder ein Bericht zum Stand der Biodiversität, und bezieht sich meist
  auf eine Gegend in Deutschland oder Gesamtdeutschland. Prüfe, ob der Text biodiversitätsbezogene
  wissenschaftliche Erkenntnisse enthält. Analysiere dafür zunächst den Rahmen der Studie / des Berichts: Um welche
  Lebensräume und Ökosystemtypen geht es? Welche Arten oder Artengruppen wurden untersucht?
  Enthält der Text Angaben zur betrachteten Biodiversitätsebene - z.B. Artenvielfalt, genetische Diversität,
  oder Habitatdiversität? Sammle diese und weitere Informationen entsprechend dem nachfolgenden
  Schema. Wenn die Studie zum Beispiel ein Überblicks-, Positions- oder Reviewpapier ist, und daher manche der
  abgefragten Informationen fehlen, lasse die entsprechenden Felder in deiner Antwort leer.

  Der Text ist als Markdown formatiert.
  Gib die Antworten auf Deutsch, auch wenn der Text auf Englisch ist.
  Wenn Antwortmöglichkeiten nach einer Frage gegeben sind, wähle nur aus den durch Semikolon getrennten Antwortmöglichkeiten.
  Extrahiere dabei nur, was auch im Text steht, konzentriere dich daher auf die Informationen, die du sicher
  identifizieren und auch belegen kannst. Für nicht im Text vorhandene Informationen lasse die entsprechenden Antwortfelder leer.
  Wenn eine Antwortmöglichkeit zutrifft, genügt es, sie einmal zu nennen, wiederhole sie also nicht mehrfach.
  Beachte jedoch auch die Angaben zur Kardinalität jedes Feldes.

  Erzeuge die Antwort in validem JSON-Format (nicht embedded Markdown!). Keine zusätzlichen Felder, keine Erklärungen.
  Gib **ausschließlich** gültiges JSON nach dem folgendem Schema zurück.

  {schema_description}

user_message: |
  Dokument in Markdown Format:

  {document}

# This indicates where to insert the schema description and the document text in the system and/or user message.
# The schema_description_placeholder should be present in a message if a schema is provided.
# The document_placeholder needs to be present in either the system or user message.
schema_description_placeholder: schema_description
document_placeholder: document
