_target_: kibad_llm.dataset.prediction.load_with_metadata
# Either specify a jsonl file or a log directory to load predictions from.
# When loading from a log directory, metadata (overrides) from the corresponding
# hydra prediction run will be attached to the dataset.
file: null
log: null

id_key: file_name
# strip file extension from predictions to match zotitem_ptr_id in references
process_id:
  _partial_: true
  _target_: kibad_llm.utils.path.strip_filename_extension
preprocess:
  _target_: kibad_llm.utils.dictionary.get
  _partial_: True
  key: "structured"
