_target_: kibad_llm.dataset.json.load_and_preprocess
file: ???
# If any of these contains a list of None values (in the first entry of the predictions),
# datasets does not grasp the structure correctly and fails, so we drop them here.
# When the extractor did return more entries that may be lists of None (e.g. reasoning_content),
# they need to be added here as well.
drop_columns:
  - error_list
preprocess:
  _target_: kibad_llm.utils.dictionary.get
  _partial_: True
  key: "structured"
