# F1 score metric for single- or multi-label classification for multiple fields.

_target_: kibad_llm.metrics.MicroF1MetricCollection
fields: ???  # the fields in the prediction and reference to compute the F1 score on
format_as_markdown: true
