# F1 score metric for single- or multi-label classification for multiple fields.

_target_: kibad_llm.metrics.F1MicroMultipleFieldsMetric
# the fields in the prediction and reference to compute the F1 score on
fields: ???
format_as_markdown: true
sort_fields: true
