# Example configuration for using GPT-OSS-20B model with LlamaIndex
#
# This requires a local deployment of the GPT-OSS-20B model that is compatible with the OpenAI API.
# See models/README.md for instructions.

# OpenAILikeVllm creates a llama_index.llms.openai_like.OpenAILike by just forwarding all provided parameters. Thus, see
# https://developers.llamaindex.ai/python/framework-api-reference/llms/openai_like/#llama_index.llms.openai_like.OpenAILike
# for available parameters.
_target_: kibad_llm.llms.OpenAILikeVllm

# get the API base URL from the environment variable LLM_API_BASE, defaulting to http://127.0.0.1:5001/v1
api_base: ${oc.env:LLM_API_BASE,http://127.0.0.1:5001/v1}
api_key: "dummy"
model: "openai/gpt-oss-20b"
# try to be as deterministic as possible
temperature: 0.0
# presence_penalty and frequency_penalty are also standard if we need them

# set maximum number of generated tokens
max_tokens: 8192
# this is the maximum context window of GPT-OSS-20B
context_window: 131072

timeout: 360 # default is 60
max_retries: 3 # the default is 3

# enable to correctly handle (i.e. remove) reasoning traces in the output
is_chat_model: true
