# Example configuration for using GPT models hosted by OpenAI with LlamaIndex.
#
# This requires an OpenAI API key with access to the specified model.
# Make sure to set the OPENAI_API_KEY environment variable before running
# by adding it to the .env file or exporting it in your shell.

# This passes all parameters to the LlamaIndex OpenAIResponse class.
# See https://developers.llamaindex.ai/python/framework-api-reference/llms/openai/#llama_index.llms.openai.OpenAIResponses
# for available parameters.
_target_: kibad_llm.llms.OpenAI

api_base: "https://api.openai.com/v1"
# If the API key is not provided here, the Llama-Index OpenAI client will internally look for it in the
# environment variable OPENAI_API_KEY. This will prevent the API key from being logged to console or files.
# Uses the token provided in /.env

model: "gpt-5"

# try to be as deterministic as possible.
# Note on temperature: As of 2026/01/05 has no effect since
# OpenAIResponses sets it to 1.0 for O1_MODELS which includes gpt-5
# See https://github.com/run-llama/llama_index/blob/220e3603dba28c4261f0d618f1672768018fb52e/llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/responses.py#L318
# temperature: 0.0
# OpenAI recommends to use `max_completion_tokens`, however, `llama_index.llms.openai.OpenAIResponses` does only support `max_output_tokens` for now
max_output_tokens: 8192
context_window: 131072

reasoning_options:
  # effort: low
  summary: auto  # summary is required to get the reasoning_content

timeout: 360
max_retries: 3

# additional args to consider:
# Note: We do not need to set 'strict=True' since that is set to True automatically in src/kibad_llm/llms/openai.py#call_llm_chat_with_guided_decoding()
# top_p: 1.0

# Add additional parameters to OpenAI request body.
#additional_kwargs:
#  # kind of redundant to max_output_tokens, but suggested by the OpenAI API
#  # Note: Does not work, throws error "Responses.create() got an unexpected keyword argument 'max_completion_tokens', ..."
#  max_completion_tokens: 8192
#  ...
