_target_: llama_index.llms.ollama.Ollama

# Ollama server and model
model: "gpt-oss:20b"
base_url: ${oc.env:OLLAMA_BASE_URL,http://127.0.0.1:11434}

# Chat/generation params
request_timeout: 360
temperature: 0.0
top_p: 1.0
num_predict: 1024
thinking: false
