# Example configuration for using Mistral-Small-3.2-24B-Instruct-2506 model with LlamaIndex
#
# This requires a local deployment of the Mistral-Small-3.2-24B-Instruct-2506 model that is compatible with the OpenAI API.
# See models/README.md for instructions.
#
# To use as an argument for `predict`, use `extractor/llm=mistral_small_3_24b`.
# Run VLLM with `./run_with_llm.sh -v "mistralai/Mistral-Small-3.2-24B-Instruct-2506 --tokenizer_mode mistral
#  --config_format mistral --load_format mistral --max-model-len 131072"`
# See https://huggingface.co/mistralai/Mistral-Small-3.2-24B-Instruct-2506 for VLLM options

_target_: kibad_llm.llms.OpenAILikeVllm

# get the API base URL from the environment variable LLM_API_BASE, defaulting to http://127.0.0.1:5001/v1
api_base: ${oc.env:LLM_API_BASE,http://127.0.0.1:5001/v1}
api_key: "dummy"
model: "mistralai/Mistral-Small-3.2-24B-Instruct-2506"
# try to be as deterministic as possible
temperature: 0.0
# presence_penalty and frequency_penalty are also standard if we need them

# enable to correctly handle (i.e. remove) reasoning traces in the output
is_chat_model: true
# Supports up to 128K tokens (max size for https://docs.mistral.ai/models/mistral-small-3-2-25-06).
# Use lower value to save memory and improve performance
context_window: 131072
timeout: 360
max_retries: 3

# Specify additional parameters to the request body.
additional_kwargs:
  # set maximum number of generated tokens
  # the default is None, so we set it to 8192, to allow enough space for reasoning and output tokens
  # see https://github.com/DFKI-NLP/kibad-llm/issues/198#issuecomment-3666155251
  # 128K is max size for https://docs.mistral.ai/models/mistral-small-3-2-25-06
  max_completion_tokens: 8192
