# Example configuration for using Qwen3-30B-A3B-Thinking-2507 model with LlamaIndex
#
# This requires a local deployment of the Qwen3-30B-A3B-Thinking-2507 model that is compatible with the OpenAI API.
# See models/README.md for instructions.
#
# To use as an argument for `predict`, use `extractor/llm=qwen3_30b`.
# Run VLLM with `./run_with_llm.sh -v "Qwen/Qwen3-30B-A3B-Thinking-2507 --max-model-len 131072
#  --reasoning-parser deepseek_r1"`
# See https://huggingface.co/Qwen/Qwen3-30B-A3B-Thinking-2507 for VLLM options

_target_: llama_index.llms.openai_like.OpenAILikeVllm

# get the API base URL from the environment variable LLM_API_BASE, defaulting to http://127.0.0.1:5001/v1
api_base: ${oc.env:LLM_API_BASE,http://127.0.0.1:5001/v1}
api_key: "dummy"
model: "Qwen/Qwen3-30B-A3B-Thinking-2507"
# try to be as deterministic as possible
temperature: 0.0
# presence_penalty and frequency_penalty are also standard if we need them

# enable to correctly handle (i.e. remove) reasoning traces in the output
is_chat_model: true
# Supports up to 256K tokens (max size for https://huggingface.co/Qwen/Qwen3-30B-A3B-Thinking-2507).
# Use lower value to save memory and improve performance
context_window: 131072
timeout: 360
max_retries: 3

# the default is None, so we set it to 8192, to allow enough space for reasoning and output tokens
# see https://github.com/DFKI-NLP/kibad-llm/issues/198#issuecomment-3666155251
# recommended are 32768 acc to https://huggingface.co/Qwen/Qwen3-30B-A3B-Thinking-2507
additional_kwargs:
  # set maximum number of generated tokens
  max_completion_tokens: 8192
