import re
from typing import Any

from llama_index.core.base.llms.types import ChatResponse
from llama_index.core.llms import ChatMessage as LlamaIndexChatMessage
from llama_index.llms.openai import OpenAI as LlamaIndexOpenAI

from kibad_llm.llms.base import LLM, SimpleChatMessage
from kibad_llm.utils.log import warn_once

_SCHEMA_NAME_RE = re.compile(r"[^a-zA-Z0-9_-]+")


def _schema_name_from(schema: dict[str, Any], default: str = "kibad_output") -> str:
    # Prefer a stable, human-readable name if present.
    name = schema.get("title") or schema.get("name") or schema.get("$id") or default
    name = str(name).split("/")[-1]  # if $id is URL-like, keep last segment
    name = _SCHEMA_NAME_RE.sub("_", name).strip("_") or default
    # OpenAI schema names are expected to be short; keep it conservative.
    return name[:64]


def make_openai_strict_json_schema(schema: dict[str, Any]) -> dict[str, Any]:
    """
    Convert a JSON Schema (often generated by Pydantic) into a form that is accepted by
    OpenAI Structured Outputs when using `response_format={"type": "json_schema", ...}`
    with `strict=True`.

    Why this exists
    ---------------
    OpenAI Structured Outputs (in strict mode) applies extra constraints on object schemas.
    In particular, for every JSON Schema object definition:

    - `additionalProperties` must be set to `false` (to forbid undeclared keys), and
    - `required` must be present and must include **every** key listed in `properties`.

    Pydantic's `model_json_schema()` typically omits fields from `required` when they have
    defaults (including `default_factory=list`), which is perfectly valid JSON Schema but
    is rejected by OpenAI's strict Structured Outputs validator.

    What the function does
    ----------------------
    This helper walks the entire schema (including nested objects and `$defs`) and, for
    each node that looks like an object schema (i.e., a dict with
    `{"type": "object", "properties": {...}}`), it:

    1. Sets `required` to `list(properties.keys())`
    2. Sets `additionalProperties` to `False`

    This makes the schema "OpenAI-strict-compatible" for structured decoding.

    Parameters
    ----------
    schema:
        A JSON Schema dictionary (e.g., from `BaseModel.model_json_schema()`).

    Returns
    -------
    dict[str, Any]
        A patched schema dictionary. The returned schema is a (shallow) copy of the input,
        but nested dictionaries/lists are modified in-place within that copy.

    Notes
    -----
    - This deliberately makes *all* fields required from OpenAI's perspective. If you want
      a field to be "optional", model it as nullable (e.g., `anyOf: [{"type": "string"},
      {"type": "null"}]`) while still listing it in `required`.
    - This function does not validate that the schema is otherwise supported by Structured
      Outputs; it only enforces the two most common strict-mode requirements.
    - The order of `required` follows the insertion order of `properties` (Python 3.7+).

    Example
    -------
    >>> raw = MyModel.model_json_schema(by_alias=False)
    >>> strict_schema = make_openai_strict_json_schema(raw)
    >>> response_format = {
    ...     "type": "json_schema",
    ...     "json_schema": {"name": "my_model", "strict": True, "schema": strict_schema},
    ... }
    """

    def walk(node: Any) -> None:
        if isinstance(node, dict):
            # Recurse first
            for v in node.values():
                walk(v)

            # Patch object nodes
            if node.get("type") == "object" and isinstance(node.get("properties"), dict):
                props = node["properties"]
                node["required"] = list(props.keys())
                node["additionalProperties"] = False

        elif isinstance(node, list):
            for item in node:
                walk(item)

    schema = dict(schema)  # shallow copy
    walk(schema)
    return schema


class OpenAI(LLM):
    """Simple wrapper around OpenAI LLMs to handle guided decoding in extractors.extract_from_text"""

    def __init__(self, *args, **kwargs) -> None:
        self.model = LlamaIndexOpenAI(*args, **kwargs)

    def call_llm_chat_with_guided_decoding(
        self,
        messages: list[SimpleChatMessage],
        *,
        json_schema: dict[str, Any] | None = None,
        **request_kwargs,
    ) -> ChatResponse:
        if json_schema is not None:
            if "response_format" in request_kwargs:
                warn_once(
                    "`json_schema` was provided but `response_format` is already set; "
                    "keeping the explicit `response_format`."
                )
            else:
                schema_name = _schema_name_from(json_schema)
                # Enforce Structured Outputs?
                # i.e. the model must adhere to this JSON Schema (not just emit valid JSON).
                strict = request_kwargs.pop("strict_json_schema", True)
                if strict:
                    # if strict is True, modify the schema to comply with OpenAI strict mode,
                    # see documentation of make_openai_strict_json_schema for details
                    json_schema = make_openai_strict_json_schema(json_schema)
                else:
                    warn_once(
                        "Using non-strict JSON Schema with OpenAI Structured Outputs "
                        "(strict_json_schema=false) is not recommended; the model may emit "
                        "keys or types not declared in the schema."
                    )
                request_kwargs["response_format"] = {
                    "type": "json_schema",
                    "json_schema": {
                        "name": schema_name,
                        "strict": strict,
                        "schema": json_schema,
                    },
                }

        llama_index_messages = [
            LlamaIndexChatMessage(role=msg.role, content=msg.content) for msg in messages
        ]
        return self.model.chat(llama_index_messages, **request_kwargs)
